Repository kirkhauck/rancid-tomatillos, pull requests merged in 2023-03, with the labels that each got.

#9 Feature/app mock state
  src/components/App/App.js
  src/index.js
  src/movieData/movieData.js
Labels: enhancement

#18 Fix/conditional movie rendering
  src/components/App/App.js
  src/components/MoviesContainer/MoviesContainer.css
Labels: bug

#26 Feature/sing movie container
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MoviesContainer/MoviesContainer.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
  src/index.css
  src/singleMovieData/singleMovie1.js
  src/singleMovieData/singleMovie2.js
Labels: enhancement

#29 feat: Add CSS to arrange components on single movie page
  src/components/MovieDetailsSection/MovieDetailsSection.css
  src/components/MovieDetailsSection/MovieDetailsSection.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
Labels: enhancement

#31 Add Fetch
  src/ApiCall.js
  src/components/App/App.js
Labels: enhancement

#34 feat: Fetch single movie's data in SingleMovieContainer
  src/ApiCall.js
  src/components/App/App.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
Labels: enhancement

#36 Add home button
  src/components/App/App.js
  src/components/ButtonHome/ButtonHome.css
  src/components/ButtonHome/ButtonHome.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
Labels: enhancement

#37 Feature/kh proptypes
  package-lock.json
  package.json
  src/components/MoviesContainer/MoviesContainer.js
  src/components/SingleMovieBanner/SingleMovieBanner.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
Labels: enhancement

#46 Add style to Home button
  src/components/ButtonHome/ButtonHome.css
  src/components/ButtonHome/ButtonHome.js
  src/components/Header/Header.css
  src/components/SingleMovieBanner/SingleMovieBanner.css
  src/components/SingleMovieContainer/SingleMovieContainer.js
Labels: enhancement

#47 Feature/add cypress
  cypress.config.js
  cypress/e2e/main_spec.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
Labels: testing

#48 Testing/sing movie container
  cypress/e2e/details_spec.cy.js
  cypress/e2e/main_spec.cy.js
  public/index.html
Labels: testing

#50 Feature/router
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/ButtonHome/ButtonHome.js
  src/components/MovieCard/MovieCard.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
  src/index.js
  src/movieData/movieData.js
  src/singleMovieData/singleMovie1.js
  src/singleMovieData/singleMovie2.js
Labels: enhancement

#57 Test/browser arrows
  cypress/e2e/arrows_spec.cy.js
Labels: testing

#58 Feature/error componant
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/SingleMovieContainer/SingleMovieContainer.js
Labels: enhancement

#59 Feature: Add sad path testing to main_spec
  cypress/e2e/main_spec.cy.js
Labels: testing

#60 feat: Add sad path testing for failed single movie fetch
  cypress/e2e/details_spec.cy.js
Labels: testing

#69 Feat: Add style to button and fixed the links on cards
  src/components/App/App.js
  src/components/ButtonHome/ButtonHome.css
  src/components/ButtonHome/ButtonHome.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/MoviesContainer/MoviesContainer.css
Labels: enhancement

#74 Feature/format card date
  cypress/e2e/details_spec.cy.js
  cypress/e2e/main_spec.cy.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
Labels: enhancement
