Repository kirkhauck/rancid-tomatillos, pull requests merged in 2023-04, with the labels that each got.

#76 Feat:clean-up-code
  cypress/e2e/home_button_spec.cy.js
  cypress/e2e/main_spec.cy.js
  src/ApiCall.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/ButtonHome/ButtonHome.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Header/Header.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetailsSection/MovieDetailsSection.css
  src/components/MovieDetailsSection/MovieDetailsSection.js
  src/components/MoviesContainer/MoviesContainer.css
  src/components/MoviesContainer/MoviesContainer.js
  src/components/SingleMovieBanner/SingleMovieBanner.css
  src/components/SingleMovieContainer/SingleMovieContainer.css
  src/components/SingleMovieContainer/SingleMovieContainer.js
  src/index.js
Labels: enhancement, testing, refactor

#78 refac: Chain test block
  cypress/e2e/details_spec.cy.js
Labels: refactor

#80 Revert "Delete spec_cy"
  cypress/e2e/spec.cy.js
Labels: refactor

#81 feat: Delete unneeded file and add vercel.json
  cypress/e2e/spec.cy.js
  vercel.json
Labels: enhancement

#82 Add: delete warnings
  src/components/ButtonHome/ButtonHome.js
  vercel.json
Labels: refactor
